# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pc-zak/Downloads/inverseCSG/a213-du/inverse_csg/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pc-zak/Downloads/inverseCSG/a213-du/inverse_csg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pc-zak/Downloads/inverseCSG/a213-du/inverse_csg/CMakeFiles /home/pc-zak/Downloads/inverseCSG/a213-du/inverse_csg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pc-zak/Downloads/inverseCSG/a213-du/inverse_csg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named csg_cpp_command

# Build rule for target.
csg_cpp_command: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_cpp_command
.PHONY : csg_cpp_command

# fast build rule for target.
csg_cpp_command/fast:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/build
.PHONY : csg_cpp_command/fast

#=============================================================================
# Target rules for targets named gco

# Build rule for target.
gco: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gco
.PHONY : gco

# fast build rule for target.
gco/fast:
	$(MAKE) -f lib/gco-v3.0/CMakeFiles/gco.dir/build.make lib/gco-v3.0/CMakeFiles/gco.dir/build
.PHONY : gco/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f lib/gco-v3.0/CMakeFiles/example.dir/build.make lib/gco-v3.0/CMakeFiles/example.dir/build
.PHONY : example/fast

src/command/add_separator_command.o: src/command/add_separator_command.cpp.o

.PHONY : src/command/add_separator_command.o

# target to build an object file
src/command/add_separator_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/add_separator_command.cpp.o
.PHONY : src/command/add_separator_command.cpp.o

src/command/add_separator_command.i: src/command/add_separator_command.cpp.i

.PHONY : src/command/add_separator_command.i

# target to preprocess a source file
src/command/add_separator_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/add_separator_command.cpp.i
.PHONY : src/command/add_separator_command.cpp.i

src/command/add_separator_command.s: src/command/add_separator_command.cpp.s

.PHONY : src/command/add_separator_command.s

# target to generate assembly for a file
src/command/add_separator_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/add_separator_command.cpp.s
.PHONY : src/command/add_separator_command.cpp.s

src/command/bhc_command.o: src/command/bhc_command.cpp.o

.PHONY : src/command/bhc_command.o

# target to build an object file
src/command/bhc_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/bhc_command.cpp.o
.PHONY : src/command/bhc_command.cpp.o

src/command/bhc_command.i: src/command/bhc_command.cpp.i

.PHONY : src/command/bhc_command.i

# target to preprocess a source file
src/command/bhc_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/bhc_command.cpp.i
.PHONY : src/command/bhc_command.cpp.i

src/command/bhc_command.s: src/command/bhc_command.cpp.s

.PHONY : src/command/bhc_command.s

# target to generate assembly for a file
src/command/bhc_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/bhc_command.cpp.s
.PHONY : src/command/bhc_command.cpp.s

src/command/clean_csg_command.o: src/command/clean_csg_command.cpp.o

.PHONY : src/command/clean_csg_command.o

# target to build an object file
src/command/clean_csg_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/clean_csg_command.cpp.o
.PHONY : src/command/clean_csg_command.cpp.o

src/command/clean_csg_command.i: src/command/clean_csg_command.cpp.i

.PHONY : src/command/clean_csg_command.i

# target to preprocess a source file
src/command/clean_csg_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/clean_csg_command.cpp.i
.PHONY : src/command/clean_csg_command.cpp.i

src/command/clean_csg_command.s: src/command/clean_csg_command.cpp.s

.PHONY : src/command/clean_csg_command.s

# target to generate assembly for a file
src/command/clean_csg_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/clean_csg_command.cpp.s
.PHONY : src/command/clean_csg_command.cpp.s

src/command/csg_flag_command.o: src/command/csg_flag_command.cpp.o

.PHONY : src/command/csg_flag_command.o

# target to build an object file
src/command/csg_flag_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/csg_flag_command.cpp.o
.PHONY : src/command/csg_flag_command.cpp.o

src/command/csg_flag_command.i: src/command/csg_flag_command.cpp.i

.PHONY : src/command/csg_flag_command.i

# target to preprocess a source file
src/command/csg_flag_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/csg_flag_command.cpp.i
.PHONY : src/command/csg_flag_command.cpp.i

src/command/csg_flag_command.s: src/command/csg_flag_command.cpp.s

.PHONY : src/command/csg_flag_command.s

# target to generate assembly for a file
src/command/csg_flag_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/csg_flag_command.cpp.s
.PHONY : src/command/csg_flag_command.cpp.s

src/command/csg_mesh_diff_command.o: src/command/csg_mesh_diff_command.cpp.o

.PHONY : src/command/csg_mesh_diff_command.o

# target to build an object file
src/command/csg_mesh_diff_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/csg_mesh_diff_command.cpp.o
.PHONY : src/command/csg_mesh_diff_command.cpp.o

src/command/csg_mesh_diff_command.i: src/command/csg_mesh_diff_command.cpp.i

.PHONY : src/command/csg_mesh_diff_command.i

# target to preprocess a source file
src/command/csg_mesh_diff_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/csg_mesh_diff_command.cpp.i
.PHONY : src/command/csg_mesh_diff_command.cpp.i

src/command/csg_mesh_diff_command.s: src/command/csg_mesh_diff_command.cpp.s

.PHONY : src/command/csg_mesh_diff_command.s

# target to generate assembly for a file
src/command/csg_mesh_diff_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/csg_mesh_diff_command.cpp.s
.PHONY : src/command/csg_mesh_diff_command.cpp.s

src/command/equiv_class_command.o: src/command/equiv_class_command.cpp.o

.PHONY : src/command/equiv_class_command.o

# target to build an object file
src/command/equiv_class_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/equiv_class_command.cpp.o
.PHONY : src/command/equiv_class_command.cpp.o

src/command/equiv_class_command.i: src/command/equiv_class_command.cpp.i

.PHONY : src/command/equiv_class_command.i

# target to preprocess a source file
src/command/equiv_class_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/equiv_class_command.cpp.i
.PHONY : src/command/equiv_class_command.cpp.i

src/command/equiv_class_command.s: src/command/equiv_class_command.cpp.s

.PHONY : src/command/equiv_class_command.s

# target to generate assembly for a file
src/command/equiv_class_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/equiv_class_command.cpp.s
.PHONY : src/command/equiv_class_command.cpp.s

src/command/equiv_class_flag_command.o: src/command/equiv_class_flag_command.cpp.o

.PHONY : src/command/equiv_class_flag_command.o

# target to build an object file
src/command/equiv_class_flag_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/equiv_class_flag_command.cpp.o
.PHONY : src/command/equiv_class_flag_command.cpp.o

src/command/equiv_class_flag_command.i: src/command/equiv_class_flag_command.cpp.i

.PHONY : src/command/equiv_class_flag_command.i

# target to preprocess a source file
src/command/equiv_class_flag_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/equiv_class_flag_command.cpp.i
.PHONY : src/command/equiv_class_flag_command.cpp.i

src/command/equiv_class_flag_command.s: src/command/equiv_class_flag_command.cpp.s

.PHONY : src/command/equiv_class_flag_command.s

# target to generate assembly for a file
src/command/equiv_class_flag_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/equiv_class_flag_command.cpp.s
.PHONY : src/command/equiv_class_flag_command.cpp.s

src/command/genetic_command.o: src/command/genetic_command.cpp.o

.PHONY : src/command/genetic_command.o

# target to build an object file
src/command/genetic_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/genetic_command.cpp.o
.PHONY : src/command/genetic_command.cpp.o

src/command/genetic_command.i: src/command/genetic_command.cpp.i

.PHONY : src/command/genetic_command.i

# target to preprocess a source file
src/command/genetic_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/genetic_command.cpp.i
.PHONY : src/command/genetic_command.cpp.i

src/command/genetic_command.s: src/command/genetic_command.cpp.s

.PHONY : src/command/genetic_command.s

# target to generate assembly for a file
src/command/genetic_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/genetic_command.cpp.s
.PHONY : src/command/genetic_command.cpp.s

src/command/hausdorff_command.o: src/command/hausdorff_command.cpp.o

.PHONY : src/command/hausdorff_command.o

# target to build an object file
src/command/hausdorff_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/hausdorff_command.cpp.o
.PHONY : src/command/hausdorff_command.cpp.o

src/command/hausdorff_command.i: src/command/hausdorff_command.cpp.i

.PHONY : src/command/hausdorff_command.i

# target to preprocess a source file
src/command/hausdorff_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/hausdorff_command.cpp.i
.PHONY : src/command/hausdorff_command.cpp.i

src/command/hausdorff_command.s: src/command/hausdorff_command.cpp.s

.PHONY : src/command/hausdorff_command.s

# target to generate assembly for a file
src/command/hausdorff_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/hausdorff_command.cpp.s
.PHONY : src/command/hausdorff_command.cpp.s

src/command/legacy_sketch_tree_command.o: src/command/legacy_sketch_tree_command.cpp.o

.PHONY : src/command/legacy_sketch_tree_command.o

# target to build an object file
src/command/legacy_sketch_tree_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/legacy_sketch_tree_command.cpp.o
.PHONY : src/command/legacy_sketch_tree_command.cpp.o

src/command/legacy_sketch_tree_command.i: src/command/legacy_sketch_tree_command.cpp.i

.PHONY : src/command/legacy_sketch_tree_command.i

# target to preprocess a source file
src/command/legacy_sketch_tree_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/legacy_sketch_tree_command.cpp.i
.PHONY : src/command/legacy_sketch_tree_command.cpp.i

src/command/legacy_sketch_tree_command.s: src/command/legacy_sketch_tree_command.cpp.s

.PHONY : src/command/legacy_sketch_tree_command.s

# target to generate assembly for a file
src/command/legacy_sketch_tree_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/legacy_sketch_tree_command.cpp.s
.PHONY : src/command/legacy_sketch_tree_command.cpp.s

src/command/level_set_command.o: src/command/level_set_command.cpp.o

.PHONY : src/command/level_set_command.o

# target to build an object file
src/command/level_set_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/level_set_command.cpp.o
.PHONY : src/command/level_set_command.cpp.o

src/command/level_set_command.i: src/command/level_set_command.cpp.i

.PHONY : src/command/level_set_command.i

# target to preprocess a source file
src/command/level_set_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/level_set_command.cpp.i
.PHONY : src/command/level_set_command.cpp.i

src/command/level_set_command.s: src/command/level_set_command.cpp.s

.PHONY : src/command/level_set_command.s

# target to generate assembly for a file
src/command/level_set_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/level_set_command.cpp.s
.PHONY : src/command/level_set_command.cpp.s

src/command/mesh_flag_command.o: src/command/mesh_flag_command.cpp.o

.PHONY : src/command/mesh_flag_command.o

# target to build an object file
src/command/mesh_flag_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/mesh_flag_command.cpp.o
.PHONY : src/command/mesh_flag_command.cpp.o

src/command/mesh_flag_command.i: src/command/mesh_flag_command.cpp.i

.PHONY : src/command/mesh_flag_command.i

# target to preprocess a source file
src/command/mesh_flag_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/mesh_flag_command.cpp.i
.PHONY : src/command/mesh_flag_command.cpp.i

src/command/mesh_flag_command.s: src/command/mesh_flag_command.cpp.s

.PHONY : src/command/mesh_flag_command.s

# target to generate assembly for a file
src/command/mesh_flag_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/mesh_flag_command.cpp.s
.PHONY : src/command/mesh_flag_command.cpp.s

src/command/primitive_command.o: src/command/primitive_command.cpp.o

.PHONY : src/command/primitive_command.o

# target to build an object file
src/command/primitive_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/primitive_command.cpp.o
.PHONY : src/command/primitive_command.cpp.o

src/command/primitive_command.i: src/command/primitive_command.cpp.i

.PHONY : src/command/primitive_command.i

# target to preprocess a source file
src/command/primitive_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/primitive_command.cpp.i
.PHONY : src/command/primitive_command.cpp.i

src/command/primitive_command.s: src/command/primitive_command.cpp.s

.PHONY : src/command/primitive_command.s

# target to generate assembly for a file
src/command/primitive_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/primitive_command.cpp.s
.PHONY : src/command/primitive_command.cpp.s

src/command/primitive_local_command.o: src/command/primitive_local_command.cpp.o

.PHONY : src/command/primitive_local_command.o

# target to build an object file
src/command/primitive_local_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/primitive_local_command.cpp.o
.PHONY : src/command/primitive_local_command.cpp.o

src/command/primitive_local_command.i: src/command/primitive_local_command.cpp.i

.PHONY : src/command/primitive_local_command.i

# target to preprocess a source file
src/command/primitive_local_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/primitive_local_command.cpp.i
.PHONY : src/command/primitive_local_command.cpp.i

src/command/primitive_local_command.s: src/command/primitive_local_command.cpp.s

.PHONY : src/command/primitive_local_command.s

# target to generate assembly for a file
src/command/primitive_local_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/primitive_local_command.cpp.s
.PHONY : src/command/primitive_local_command.cpp.s

src/command/ransac_command.o: src/command/ransac_command.cpp.o

.PHONY : src/command/ransac_command.o

# target to build an object file
src/command/ransac_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/ransac_command.cpp.o
.PHONY : src/command/ransac_command.cpp.o

src/command/ransac_command.i: src/command/ransac_command.cpp.i

.PHONY : src/command/ransac_command.i

# target to preprocess a source file
src/command/ransac_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/ransac_command.cpp.i
.PHONY : src/command/ransac_command.cpp.i

src/command/ransac_command.s: src/command/ransac_command.cpp.s

.PHONY : src/command/ransac_command.s

# target to generate assembly for a file
src/command/ransac_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/ransac_command.cpp.s
.PHONY : src/command/ransac_command.cpp.s

src/command/remove_equiv_class_command.o: src/command/remove_equiv_class_command.cpp.o

.PHONY : src/command/remove_equiv_class_command.o

# target to build an object file
src/command/remove_equiv_class_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/remove_equiv_class_command.cpp.o
.PHONY : src/command/remove_equiv_class_command.cpp.o

src/command/remove_equiv_class_command.i: src/command/remove_equiv_class_command.cpp.i

.PHONY : src/command/remove_equiv_class_command.i

# target to preprocess a source file
src/command/remove_equiv_class_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/remove_equiv_class_command.cpp.i
.PHONY : src/command/remove_equiv_class_command.cpp.i

src/command/remove_equiv_class_command.s: src/command/remove_equiv_class_command.cpp.s

.PHONY : src/command/remove_equiv_class_command.s

# target to generate assembly for a file
src/command/remove_equiv_class_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/remove_equiv_class_command.cpp.s
.PHONY : src/command/remove_equiv_class_command.cpp.s

src/command/remove_prim_command.o: src/command/remove_prim_command.cpp.o

.PHONY : src/command/remove_prim_command.o

# target to build an object file
src/command/remove_prim_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/remove_prim_command.cpp.o
.PHONY : src/command/remove_prim_command.cpp.o

src/command/remove_prim_command.i: src/command/remove_prim_command.cpp.i

.PHONY : src/command/remove_prim_command.i

# target to preprocess a source file
src/command/remove_prim_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/remove_prim_command.cpp.i
.PHONY : src/command/remove_prim_command.cpp.i

src/command/remove_prim_command.s: src/command/remove_prim_command.cpp.s

.PHONY : src/command/remove_prim_command.s

# target to generate assembly for a file
src/command/remove_prim_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/remove_prim_command.cpp.s
.PHONY : src/command/remove_prim_command.cpp.s

src/command/surface_sample_command.o: src/command/surface_sample_command.cpp.o

.PHONY : src/command/surface_sample_command.o

# target to build an object file
src/command/surface_sample_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/surface_sample_command.cpp.o
.PHONY : src/command/surface_sample_command.cpp.o

src/command/surface_sample_command.i: src/command/surface_sample_command.cpp.i

.PHONY : src/command/surface_sample_command.i

# target to preprocess a source file
src/command/surface_sample_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/surface_sample_command.cpp.i
.PHONY : src/command/surface_sample_command.cpp.i

src/command/surface_sample_command.s: src/command/surface_sample_command.cpp.s

.PHONY : src/command/surface_sample_command.s

# target to generate assembly for a file
src/command/surface_sample_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/surface_sample_command.cpp.s
.PHONY : src/command/surface_sample_command.cpp.s

src/command/traverse_tree_command.o: src/command/traverse_tree_command.cpp.o

.PHONY : src/command/traverse_tree_command.o

# target to build an object file
src/command/traverse_tree_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/traverse_tree_command.cpp.o
.PHONY : src/command/traverse_tree_command.cpp.o

src/command/traverse_tree_command.i: src/command/traverse_tree_command.cpp.i

.PHONY : src/command/traverse_tree_command.i

# target to preprocess a source file
src/command/traverse_tree_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/traverse_tree_command.cpp.i
.PHONY : src/command/traverse_tree_command.cpp.i

src/command/traverse_tree_command.s: src/command/traverse_tree_command.cpp.s

.PHONY : src/command/traverse_tree_command.s

# target to generate assembly for a file
src/command/traverse_tree_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/traverse_tree_command.cpp.s
.PHONY : src/command/traverse_tree_command.cpp.s

src/command/tree_info_command.o: src/command/tree_info_command.cpp.o

.PHONY : src/command/tree_info_command.o

# target to build an object file
src/command/tree_info_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/tree_info_command.cpp.o
.PHONY : src/command/tree_info_command.cpp.o

src/command/tree_info_command.i: src/command/tree_info_command.cpp.i

.PHONY : src/command/tree_info_command.i

# target to preprocess a source file
src/command/tree_info_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/tree_info_command.cpp.i
.PHONY : src/command/tree_info_command.cpp.i

src/command/tree_info_command.s: src/command/tree_info_command.cpp.s

.PHONY : src/command/tree_info_command.s

# target to generate assembly for a file
src/command/tree_info_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/tree_info_command.cpp.s
.PHONY : src/command/tree_info_command.cpp.s

src/command/volume_sample_command.o: src/command/volume_sample_command.cpp.o

.PHONY : src/command/volume_sample_command.o

# target to build an object file
src/command/volume_sample_command.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/volume_sample_command.cpp.o
.PHONY : src/command/volume_sample_command.cpp.o

src/command/volume_sample_command.i: src/command/volume_sample_command.cpp.i

.PHONY : src/command/volume_sample_command.i

# target to preprocess a source file
src/command/volume_sample_command.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/volume_sample_command.cpp.i
.PHONY : src/command/volume_sample_command.cpp.i

src/command/volume_sample_command.s: src/command/volume_sample_command.cpp.s

.PHONY : src/command/volume_sample_command.s

# target to generate assembly for a file
src/command/volume_sample_command.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/command/volume_sample_command.cpp.s
.PHONY : src/command/volume_sample_command.cpp.s

src/common/arg_parser.o: src/common/arg_parser.cpp.o

.PHONY : src/common/arg_parser.o

# target to build an object file
src/common/arg_parser.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/arg_parser.cpp.o
.PHONY : src/common/arg_parser.cpp.o

src/common/arg_parser.i: src/common/arg_parser.cpp.i

.PHONY : src/common/arg_parser.i

# target to preprocess a source file
src/common/arg_parser.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/arg_parser.cpp.i
.PHONY : src/common/arg_parser.cpp.i

src/common/arg_parser.s: src/common/arg_parser.cpp.s

.PHONY : src/common/arg_parser.s

# target to generate assembly for a file
src/common/arg_parser.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/arg_parser.cpp.s
.PHONY : src/common/arg_parser.cpp.s

src/common/file_helper.o: src/common/file_helper.cpp.o

.PHONY : src/common/file_helper.o

# target to build an object file
src/common/file_helper.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/file_helper.cpp.o
.PHONY : src/common/file_helper.cpp.o

src/common/file_helper.i: src/common/file_helper.cpp.i

.PHONY : src/common/file_helper.i

# target to preprocess a source file
src/common/file_helper.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/file_helper.cpp.i
.PHONY : src/common/file_helper.cpp.i

src/common/file_helper.s: src/common/file_helper.cpp.s

.PHONY : src/common/file_helper.s

# target to generate assembly for a file
src/common/file_helper.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/file_helper.cpp.s
.PHONY : src/common/file_helper.cpp.s

src/common/math_helper.o: src/common/math_helper.cpp.o

.PHONY : src/common/math_helper.o

# target to build an object file
src/common/math_helper.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/math_helper.cpp.o
.PHONY : src/common/math_helper.cpp.o

src/common/math_helper.i: src/common/math_helper.cpp.i

.PHONY : src/common/math_helper.i

# target to preprocess a source file
src/common/math_helper.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/math_helper.cpp.i
.PHONY : src/common/math_helper.cpp.i

src/common/math_helper.s: src/common/math_helper.cpp.s

.PHONY : src/common/math_helper.s

# target to generate assembly for a file
src/common/math_helper.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/math_helper.cpp.s
.PHONY : src/common/math_helper.cpp.s

src/common/polynomial.o: src/common/polynomial.cpp.o

.PHONY : src/common/polynomial.o

# target to build an object file
src/common/polynomial.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/polynomial.cpp.o
.PHONY : src/common/polynomial.cpp.o

src/common/polynomial.i: src/common/polynomial.cpp.i

.PHONY : src/common/polynomial.i

# target to preprocess a source file
src/common/polynomial.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/polynomial.cpp.i
.PHONY : src/common/polynomial.cpp.i

src/common/polynomial.s: src/common/polynomial.cpp.s

.PHONY : src/common/polynomial.s

# target to generate assembly for a file
src/common/polynomial.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/common/polynomial.cpp.s
.PHONY : src/common/polynomial.cpp.s

src/csg/csg_cone_node.o: src/csg/csg_cone_node.cpp.o

.PHONY : src/csg/csg_cone_node.o

# target to build an object file
src/csg/csg_cone_node.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_cone_node.cpp.o
.PHONY : src/csg/csg_cone_node.cpp.o

src/csg/csg_cone_node.i: src/csg/csg_cone_node.cpp.i

.PHONY : src/csg/csg_cone_node.i

# target to preprocess a source file
src/csg/csg_cone_node.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_cone_node.cpp.i
.PHONY : src/csg/csg_cone_node.cpp.i

src/csg/csg_cone_node.s: src/csg/csg_cone_node.cpp.s

.PHONY : src/csg/csg_cone_node.s

# target to generate assembly for a file
src/csg/csg_cone_node.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_cone_node.cpp.s
.PHONY : src/csg/csg_cone_node.cpp.s

src/csg/csg_cube_node.o: src/csg/csg_cube_node.cpp.o

.PHONY : src/csg/csg_cube_node.o

# target to build an object file
src/csg/csg_cube_node.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_cube_node.cpp.o
.PHONY : src/csg/csg_cube_node.cpp.o

src/csg/csg_cube_node.i: src/csg/csg_cube_node.cpp.i

.PHONY : src/csg/csg_cube_node.i

# target to preprocess a source file
src/csg/csg_cube_node.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_cube_node.cpp.i
.PHONY : src/csg/csg_cube_node.cpp.i

src/csg/csg_cube_node.s: src/csg/csg_cube_node.cpp.s

.PHONY : src/csg/csg_cube_node.s

# target to generate assembly for a file
src/csg/csg_cube_node.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_cube_node.cpp.s
.PHONY : src/csg/csg_cube_node.cpp.s

src/csg/csg_cylinder_node.o: src/csg/csg_cylinder_node.cpp.o

.PHONY : src/csg/csg_cylinder_node.o

# target to build an object file
src/csg/csg_cylinder_node.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_cylinder_node.cpp.o
.PHONY : src/csg/csg_cylinder_node.cpp.o

src/csg/csg_cylinder_node.i: src/csg/csg_cylinder_node.cpp.i

.PHONY : src/csg/csg_cylinder_node.i

# target to preprocess a source file
src/csg/csg_cylinder_node.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_cylinder_node.cpp.i
.PHONY : src/csg/csg_cylinder_node.cpp.i

src/csg/csg_cylinder_node.s: src/csg/csg_cylinder_node.cpp.s

.PHONY : src/csg/csg_cylinder_node.s

# target to generate assembly for a file
src/csg/csg_cylinder_node.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_cylinder_node.cpp.s
.PHONY : src/csg/csg_cylinder_node.cpp.s

src/csg/csg_internal_node.o: src/csg/csg_internal_node.cpp.o

.PHONY : src/csg/csg_internal_node.o

# target to build an object file
src/csg/csg_internal_node.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_internal_node.cpp.o
.PHONY : src/csg/csg_internal_node.cpp.o

src/csg/csg_internal_node.i: src/csg/csg_internal_node.cpp.i

.PHONY : src/csg/csg_internal_node.i

# target to preprocess a source file
src/csg/csg_internal_node.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_internal_node.cpp.i
.PHONY : src/csg/csg_internal_node.cpp.i

src/csg/csg_internal_node.s: src/csg/csg_internal_node.cpp.s

.PHONY : src/csg/csg_internal_node.s

# target to generate assembly for a file
src/csg/csg_internal_node.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_internal_node.cpp.s
.PHONY : src/csg/csg_internal_node.cpp.s

src/csg/csg_node.o: src/csg/csg_node.cpp.o

.PHONY : src/csg/csg_node.o

# target to build an object file
src/csg/csg_node.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_node.cpp.o
.PHONY : src/csg/csg_node.cpp.o

src/csg/csg_node.i: src/csg/csg_node.cpp.i

.PHONY : src/csg/csg_node.i

# target to preprocess a source file
src/csg/csg_node.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_node.cpp.i
.PHONY : src/csg/csg_node.cpp.i

src/csg/csg_node.s: src/csg/csg_node.cpp.s

.PHONY : src/csg/csg_node.s

# target to generate assembly for a file
src/csg/csg_node.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_node.cpp.s
.PHONY : src/csg/csg_node.cpp.s

src/csg/csg_sphere_node.o: src/csg/csg_sphere_node.cpp.o

.PHONY : src/csg/csg_sphere_node.o

# target to build an object file
src/csg/csg_sphere_node.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_sphere_node.cpp.o
.PHONY : src/csg/csg_sphere_node.cpp.o

src/csg/csg_sphere_node.i: src/csg/csg_sphere_node.cpp.i

.PHONY : src/csg/csg_sphere_node.i

# target to preprocess a source file
src/csg/csg_sphere_node.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_sphere_node.cpp.i
.PHONY : src/csg/csg_sphere_node.cpp.i

src/csg/csg_sphere_node.s: src/csg/csg_sphere_node.cpp.s

.PHONY : src/csg/csg_sphere_node.s

# target to generate assembly for a file
src/csg/csg_sphere_node.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_sphere_node.cpp.s
.PHONY : src/csg/csg_sphere_node.cpp.s

src/csg/csg_torus_node.o: src/csg/csg_torus_node.cpp.o

.PHONY : src/csg/csg_torus_node.o

# target to build an object file
src/csg/csg_torus_node.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_torus_node.cpp.o
.PHONY : src/csg/csg_torus_node.cpp.o

src/csg/csg_torus_node.i: src/csg/csg_torus_node.cpp.i

.PHONY : src/csg/csg_torus_node.i

# target to preprocess a source file
src/csg/csg_torus_node.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_torus_node.cpp.i
.PHONY : src/csg/csg_torus_node.cpp.i

src/csg/csg_torus_node.s: src/csg/csg_torus_node.cpp.s

.PHONY : src/csg/csg_torus_node.s

# target to generate assembly for a file
src/csg/csg_torus_node.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/csg_torus_node.cpp.s
.PHONY : src/csg/csg_torus_node.cpp.s

src/csg/scad_file_parser.o: src/csg/scad_file_parser.cpp.o

.PHONY : src/csg/scad_file_parser.o

# target to build an object file
src/csg/scad_file_parser.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/scad_file_parser.cpp.o
.PHONY : src/csg/scad_file_parser.cpp.o

src/csg/scad_file_parser.i: src/csg/scad_file_parser.cpp.i

.PHONY : src/csg/scad_file_parser.i

# target to preprocess a source file
src/csg/scad_file_parser.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/scad_file_parser.cpp.i
.PHONY : src/csg/scad_file_parser.cpp.i

src/csg/scad_file_parser.s: src/csg/scad_file_parser.cpp.s

.PHONY : src/csg/scad_file_parser.s

# target to generate assembly for a file
src/csg/scad_file_parser.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/csg/scad_file_parser.cpp.s
.PHONY : src/csg/scad_file_parser.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mesh/intersection.o: src/mesh/intersection.cpp.o

.PHONY : src/mesh/intersection.o

# target to build an object file
src/mesh/intersection.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/intersection.cpp.o
.PHONY : src/mesh/intersection.cpp.o

src/mesh/intersection.i: src/mesh/intersection.cpp.i

.PHONY : src/mesh/intersection.i

# target to preprocess a source file
src/mesh/intersection.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/intersection.cpp.i
.PHONY : src/mesh/intersection.cpp.i

src/mesh/intersection.s: src/mesh/intersection.cpp.s

.PHONY : src/mesh/intersection.s

# target to generate assembly for a file
src/mesh/intersection.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/intersection.cpp.s
.PHONY : src/mesh/intersection.cpp.s

src/mesh/kd_tree.o: src/mesh/kd_tree.cpp.o

.PHONY : src/mesh/kd_tree.o

# target to build an object file
src/mesh/kd_tree.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/kd_tree.cpp.o
.PHONY : src/mesh/kd_tree.cpp.o

src/mesh/kd_tree.i: src/mesh/kd_tree.cpp.i

.PHONY : src/mesh/kd_tree.i

# target to preprocess a source file
src/mesh/kd_tree.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/kd_tree.cpp.i
.PHONY : src/mesh/kd_tree.cpp.i

src/mesh/kd_tree.s: src/mesh/kd_tree.cpp.s

.PHONY : src/mesh/kd_tree.s

# target to generate assembly for a file
src/mesh/kd_tree.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/kd_tree.cpp.s
.PHONY : src/mesh/kd_tree.cpp.s

src/mesh/kd_tree_node.o: src/mesh/kd_tree_node.cpp.o

.PHONY : src/mesh/kd_tree_node.o

# target to build an object file
src/mesh/kd_tree_node.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/kd_tree_node.cpp.o
.PHONY : src/mesh/kd_tree_node.cpp.o

src/mesh/kd_tree_node.i: src/mesh/kd_tree_node.cpp.i

.PHONY : src/mesh/kd_tree_node.i

# target to preprocess a source file
src/mesh/kd_tree_node.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/kd_tree_node.cpp.i
.PHONY : src/mesh/kd_tree_node.cpp.i

src/mesh/kd_tree_node.s: src/mesh/kd_tree_node.cpp.s

.PHONY : src/mesh/kd_tree_node.s

# target to generate assembly for a file
src/mesh/kd_tree_node.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/kd_tree_node.cpp.s
.PHONY : src/mesh/kd_tree_node.cpp.s

src/mesh/level_set_helper.o: src/mesh/level_set_helper.cpp.o

.PHONY : src/mesh/level_set_helper.o

# target to build an object file
src/mesh/level_set_helper.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/level_set_helper.cpp.o
.PHONY : src/mesh/level_set_helper.cpp.o

src/mesh/level_set_helper.i: src/mesh/level_set_helper.cpp.i

.PHONY : src/mesh/level_set_helper.i

# target to preprocess a source file
src/mesh/level_set_helper.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/level_set_helper.cpp.i
.PHONY : src/mesh/level_set_helper.cpp.i

src/mesh/level_set_helper.s: src/mesh/level_set_helper.cpp.s

.PHONY : src/mesh/level_set_helper.s

# target to generate assembly for a file
src/mesh/level_set_helper.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/level_set_helper.cpp.s
.PHONY : src/mesh/level_set_helper.cpp.s

src/mesh/tri_mesh.o: src/mesh/tri_mesh.cpp.o

.PHONY : src/mesh/tri_mesh.o

# target to build an object file
src/mesh/tri_mesh.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/tri_mesh.cpp.o
.PHONY : src/mesh/tri_mesh.cpp.o

src/mesh/tri_mesh.i: src/mesh/tri_mesh.cpp.i

.PHONY : src/mesh/tri_mesh.i

# target to preprocess a source file
src/mesh/tri_mesh.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/tri_mesh.cpp.i
.PHONY : src/mesh/tri_mesh.cpp.i

src/mesh/tri_mesh.s: src/mesh/tri_mesh.cpp.s

.PHONY : src/mesh/tri_mesh.s

# target to generate assembly for a file
src/mesh/tri_mesh.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/mesh/tri_mesh.cpp.s
.PHONY : src/mesh/tri_mesh.cpp.s

src/primitive/conical_surface.o: src/primitive/conical_surface.cpp.o

.PHONY : src/primitive/conical_surface.o

# target to build an object file
src/primitive/conical_surface.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/conical_surface.cpp.o
.PHONY : src/primitive/conical_surface.cpp.o

src/primitive/conical_surface.i: src/primitive/conical_surface.cpp.i

.PHONY : src/primitive/conical_surface.i

# target to preprocess a source file
src/primitive/conical_surface.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/conical_surface.cpp.i
.PHONY : src/primitive/conical_surface.cpp.i

src/primitive/conical_surface.s: src/primitive/conical_surface.cpp.s

.PHONY : src/primitive/conical_surface.s

# target to generate assembly for a file
src/primitive/conical_surface.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/conical_surface.cpp.s
.PHONY : src/primitive/conical_surface.cpp.s

src/primitive/cylindrical_surface.o: src/primitive/cylindrical_surface.cpp.o

.PHONY : src/primitive/cylindrical_surface.o

# target to build an object file
src/primitive/cylindrical_surface.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/cylindrical_surface.cpp.o
.PHONY : src/primitive/cylindrical_surface.cpp.o

src/primitive/cylindrical_surface.i: src/primitive/cylindrical_surface.cpp.i

.PHONY : src/primitive/cylindrical_surface.i

# target to preprocess a source file
src/primitive/cylindrical_surface.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/cylindrical_surface.cpp.i
.PHONY : src/primitive/cylindrical_surface.cpp.i

src/primitive/cylindrical_surface.s: src/primitive/cylindrical_surface.cpp.s

.PHONY : src/primitive/cylindrical_surface.s

# target to generate assembly for a file
src/primitive/cylindrical_surface.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/cylindrical_surface.cpp.s
.PHONY : src/primitive/cylindrical_surface.cpp.s

src/primitive/plane_surface.o: src/primitive/plane_surface.cpp.o

.PHONY : src/primitive/plane_surface.o

# target to build an object file
src/primitive/plane_surface.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/plane_surface.cpp.o
.PHONY : src/primitive/plane_surface.cpp.o

src/primitive/plane_surface.i: src/primitive/plane_surface.cpp.i

.PHONY : src/primitive/plane_surface.i

# target to preprocess a source file
src/primitive/plane_surface.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/plane_surface.cpp.i
.PHONY : src/primitive/plane_surface.cpp.i

src/primitive/plane_surface.s: src/primitive/plane_surface.cpp.s

.PHONY : src/primitive/plane_surface.s

# target to generate assembly for a file
src/primitive/plane_surface.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/plane_surface.cpp.s
.PHONY : src/primitive/plane_surface.cpp.s

src/primitive/spherical_surface.o: src/primitive/spherical_surface.cpp.o

.PHONY : src/primitive/spherical_surface.o

# target to build an object file
src/primitive/spherical_surface.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/spherical_surface.cpp.o
.PHONY : src/primitive/spherical_surface.cpp.o

src/primitive/spherical_surface.i: src/primitive/spherical_surface.cpp.i

.PHONY : src/primitive/spherical_surface.i

# target to preprocess a source file
src/primitive/spherical_surface.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/spherical_surface.cpp.i
.PHONY : src/primitive/spherical_surface.cpp.i

src/primitive/spherical_surface.s: src/primitive/spherical_surface.cpp.s

.PHONY : src/primitive/spherical_surface.s

# target to generate assembly for a file
src/primitive/spherical_surface.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/spherical_surface.cpp.s
.PHONY : src/primitive/spherical_surface.cpp.s

src/primitive/surface_primitive.o: src/primitive/surface_primitive.cpp.o

.PHONY : src/primitive/surface_primitive.o

# target to build an object file
src/primitive/surface_primitive.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/surface_primitive.cpp.o
.PHONY : src/primitive/surface_primitive.cpp.o

src/primitive/surface_primitive.i: src/primitive/surface_primitive.cpp.i

.PHONY : src/primitive/surface_primitive.i

# target to preprocess a source file
src/primitive/surface_primitive.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/surface_primitive.cpp.i
.PHONY : src/primitive/surface_primitive.cpp.i

src/primitive/surface_primitive.s: src/primitive/surface_primitive.cpp.s

.PHONY : src/primitive/surface_primitive.s

# target to generate assembly for a file
src/primitive/surface_primitive.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/surface_primitive.cpp.s
.PHONY : src/primitive/surface_primitive.cpp.s

src/primitive/toric_surface.o: src/primitive/toric_surface.cpp.o

.PHONY : src/primitive/toric_surface.o

# target to build an object file
src/primitive/toric_surface.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/toric_surface.cpp.o
.PHONY : src/primitive/toric_surface.cpp.o

src/primitive/toric_surface.i: src/primitive/toric_surface.cpp.i

.PHONY : src/primitive/toric_surface.i

# target to preprocess a source file
src/primitive/toric_surface.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/toric_surface.cpp.i
.PHONY : src/primitive/toric_surface.cpp.i

src/primitive/toric_surface.s: src/primitive/toric_surface.cpp.s

.PHONY : src/primitive/toric_surface.s

# target to generate assembly for a file
src/primitive/toric_surface.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/primitive/toric_surface.cpp.s
.PHONY : src/primitive/toric_surface.cpp.s

src/ransac/cgal_ransac_wrapper.o: src/ransac/cgal_ransac_wrapper.cpp.o

.PHONY : src/ransac/cgal_ransac_wrapper.o

# target to build an object file
src/ransac/cgal_ransac_wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/ransac/cgal_ransac_wrapper.cpp.o
.PHONY : src/ransac/cgal_ransac_wrapper.cpp.o

src/ransac/cgal_ransac_wrapper.i: src/ransac/cgal_ransac_wrapper.cpp.i

.PHONY : src/ransac/cgal_ransac_wrapper.i

# target to preprocess a source file
src/ransac/cgal_ransac_wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/ransac/cgal_ransac_wrapper.cpp.i
.PHONY : src/ransac/cgal_ransac_wrapper.cpp.i

src/ransac/cgal_ransac_wrapper.s: src/ransac/cgal_ransac_wrapper.cpp.s

.PHONY : src/ransac/cgal_ransac_wrapper.s

# target to generate assembly for a file
src/ransac/cgal_ransac_wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/ransac/cgal_ransac_wrapper.cpp.s
.PHONY : src/ransac/cgal_ransac_wrapper.cpp.s

src/test/test.o: src/test/test.cpp.o

.PHONY : src/test/test.o

# target to build an object file
src/test/test.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test.cpp.o
.PHONY : src/test/test.cpp.o

src/test/test.i: src/test/test.cpp.i

.PHONY : src/test/test.i

# target to preprocess a source file
src/test/test.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test.cpp.i
.PHONY : src/test/test.cpp.i

src/test/test.s: src/test/test.cpp.s

.PHONY : src/test/test.s

# target to generate assembly for a file
src/test/test.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test.cpp.s
.PHONY : src/test/test.cpp.s

src/test/test_compute_level_set.o: src/test/test_compute_level_set.cpp.o

.PHONY : src/test/test_compute_level_set.o

# target to build an object file
src/test/test_compute_level_set.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_compute_level_set.cpp.o
.PHONY : src/test/test_compute_level_set.cpp.o

src/test/test_compute_level_set.i: src/test/test_compute_level_set.cpp.i

.PHONY : src/test/test_compute_level_set.i

# target to preprocess a source file
src/test/test_compute_level_set.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_compute_level_set.cpp.i
.PHONY : src/test/test_compute_level_set.cpp.i

src/test/test_compute_level_set.s: src/test/test_compute_level_set.cpp.s

.PHONY : src/test/test_compute_level_set.s

# target to generate assembly for a file
src/test/test_compute_level_set.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_compute_level_set.cpp.s
.PHONY : src/test/test_compute_level_set.cpp.s

src/test/test_generate_random_ints.o: src/test/test_generate_random_ints.cpp.o

.PHONY : src/test/test_generate_random_ints.o

# target to build an object file
src/test/test_generate_random_ints.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_generate_random_ints.cpp.o
.PHONY : src/test/test_generate_random_ints.cpp.o

src/test/test_generate_random_ints.i: src/test/test_generate_random_ints.cpp.i

.PHONY : src/test/test_generate_random_ints.i

# target to preprocess a source file
src/test/test_generate_random_ints.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_generate_random_ints.cpp.i
.PHONY : src/test/test_generate_random_ints.cpp.i

src/test/test_generate_random_ints.s: src/test/test_generate_random_ints.cpp.s

.PHONY : src/test/test_generate_random_ints.s

# target to generate assembly for a file
src/test/test_generate_random_ints.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_generate_random_ints.cpp.s
.PHONY : src/test/test_generate_random_ints.cpp.s

src/test/test_grad_norm_vector.o: src/test/test_grad_norm_vector.cpp.o

.PHONY : src/test/test_grad_norm_vector.o

# target to build an object file
src/test/test_grad_norm_vector.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_grad_norm_vector.cpp.o
.PHONY : src/test/test_grad_norm_vector.cpp.o

src/test/test_grad_norm_vector.i: src/test/test_grad_norm_vector.cpp.i

.PHONY : src/test/test_grad_norm_vector.i

# target to preprocess a source file
src/test/test_grad_norm_vector.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_grad_norm_vector.cpp.i
.PHONY : src/test/test_grad_norm_vector.cpp.i

src/test/test_grad_norm_vector.s: src/test/test_grad_norm_vector.cpp.s

.PHONY : src/test/test_grad_norm_vector.s

# target to generate assembly for a file
src/test/test_grad_norm_vector.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_grad_norm_vector.cpp.s
.PHONY : src/test/test_grad_norm_vector.cpp.s

src/test/test_initialize_surface_parameters.o: src/test/test_initialize_surface_parameters.cpp.o

.PHONY : src/test/test_initialize_surface_parameters.o

# target to build an object file
src/test/test_initialize_surface_parameters.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_initialize_surface_parameters.cpp.o
.PHONY : src/test/test_initialize_surface_parameters.cpp.o

src/test/test_initialize_surface_parameters.i: src/test/test_initialize_surface_parameters.cpp.i

.PHONY : src/test/test_initialize_surface_parameters.i

# target to preprocess a source file
src/test/test_initialize_surface_parameters.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_initialize_surface_parameters.cpp.i
.PHONY : src/test/test_initialize_surface_parameters.cpp.i

src/test/test_initialize_surface_parameters.s: src/test/test_initialize_surface_parameters.cpp.s

.PHONY : src/test/test_initialize_surface_parameters.s

# target to generate assembly for a file
src/test/test_initialize_surface_parameters.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_initialize_surface_parameters.cpp.s
.PHONY : src/test/test_initialize_surface_parameters.cpp.s

src/test/test_integral.o: src/test/test_integral.cpp.o

.PHONY : src/test/test_integral.o

# target to build an object file
src/test/test_integral.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_integral.cpp.o
.PHONY : src/test/test_integral.cpp.o

src/test/test_integral.i: src/test/test_integral.cpp.i

.PHONY : src/test/test_integral.i

# target to preprocess a source file
src/test/test_integral.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_integral.cpp.i
.PHONY : src/test/test_integral.cpp.i

src/test/test_integral.s: src/test/test_integral.cpp.s

.PHONY : src/test/test_integral.s

# target to generate assembly for a file
src/test/test_integral.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_integral.cpp.s
.PHONY : src/test/test_integral.cpp.s

src/test/test_intersect.o: src/test/test_intersect.cpp.o

.PHONY : src/test/test_intersect.o

# target to build an object file
src/test/test_intersect.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_intersect.cpp.o
.PHONY : src/test/test_intersect.cpp.o

src/test/test_intersect.i: src/test/test_intersect.cpp.i

.PHONY : src/test/test_intersect.i

# target to preprocess a source file
src/test/test_intersect.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_intersect.cpp.i
.PHONY : src/test/test_intersect.cpp.i

src/test/test_intersect.s: src/test/test_intersect.cpp.s

.PHONY : src/test/test_intersect.s

# target to generate assembly for a file
src/test/test_intersect.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_intersect.cpp.s
.PHONY : src/test/test_intersect.cpp.s

src/test/test_is_inside.o: src/test/test_is_inside.cpp.o

.PHONY : src/test/test_is_inside.o

# target to build an object file
src/test/test_is_inside.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_is_inside.cpp.o
.PHONY : src/test/test_is_inside.cpp.o

src/test/test_is_inside.i: src/test/test_is_inside.cpp.i

.PHONY : src/test/test_is_inside.i

# target to preprocess a source file
src/test/test_is_inside.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_is_inside.cpp.i
.PHONY : src/test/test_is_inside.cpp.i

src/test/test_is_inside.s: src/test/test_is_inside.cpp.s

.PHONY : src/test/test_is_inside.s

# target to generate assembly for a file
src/test/test_is_inside.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_is_inside.cpp.s
.PHONY : src/test/test_is_inside.cpp.s

src/test/test_l21_matrix.o: src/test/test_l21_matrix.cpp.o

.PHONY : src/test/test_l21_matrix.o

# target to build an object file
src/test/test_l21_matrix.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_l21_matrix.cpp.o
.PHONY : src/test/test_l21_matrix.cpp.o

src/test/test_l21_matrix.i: src/test/test_l21_matrix.cpp.i

.PHONY : src/test/test_l21_matrix.i

# target to preprocess a source file
src/test/test_l21_matrix.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_l21_matrix.cpp.i
.PHONY : src/test/test_l21_matrix.cpp.i

src/test/test_l21_matrix.s: src/test/test_l21_matrix.cpp.s

.PHONY : src/test/test_l21_matrix.s

# target to generate assembly for a file
src/test/test_l21_matrix.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_l21_matrix.cpp.s
.PHONY : src/test/test_l21_matrix.cpp.s

src/test/test_l2_matrix.o: src/test/test_l2_matrix.cpp.o

.PHONY : src/test/test_l2_matrix.o

# target to build an object file
src/test/test_l2_matrix.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_l2_matrix.cpp.o
.PHONY : src/test/test_l2_matrix.cpp.o

src/test/test_l2_matrix.i: src/test/test_l2_matrix.cpp.i

.PHONY : src/test/test_l2_matrix.i

# target to preprocess a source file
src/test/test_l2_matrix.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_l2_matrix.cpp.i
.PHONY : src/test/test_l2_matrix.cpp.i

src/test/test_l2_matrix.s: src/test/test_l2_matrix.cpp.s

.PHONY : src/test/test_l2_matrix.s

# target to generate assembly for a file
src/test/test_l2_matrix.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_l2_matrix.cpp.s
.PHONY : src/test/test_l2_matrix.cpp.s

src/test/test_linear_least_square_plane_fit.o: src/test/test_linear_least_square_plane_fit.cpp.o

.PHONY : src/test/test_linear_least_square_plane_fit.o

# target to build an object file
src/test/test_linear_least_square_plane_fit.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_linear_least_square_plane_fit.cpp.o
.PHONY : src/test/test_linear_least_square_plane_fit.cpp.o

src/test/test_linear_least_square_plane_fit.i: src/test/test_linear_least_square_plane_fit.cpp.i

.PHONY : src/test/test_linear_least_square_plane_fit.i

# target to preprocess a source file
src/test/test_linear_least_square_plane_fit.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_linear_least_square_plane_fit.cpp.i
.PHONY : src/test/test_linear_least_square_plane_fit.cpp.i

src/test/test_linear_least_square_plane_fit.s: src/test/test_linear_least_square_plane_fit.cpp.s

.PHONY : src/test/test_linear_least_square_plane_fit.s

# target to generate assembly for a file
src/test/test_linear_least_square_plane_fit.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_linear_least_square_plane_fit.cpp.s
.PHONY : src/test/test_linear_least_square_plane_fit.cpp.s

src/test/test_polynomial_roots.o: src/test/test_polynomial_roots.cpp.o

.PHONY : src/test/test_polynomial_roots.o

# target to build an object file
src/test/test_polynomial_roots.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_polynomial_roots.cpp.o
.PHONY : src/test/test_polynomial_roots.cpp.o

src/test/test_polynomial_roots.i: src/test/test_polynomial_roots.cpp.i

.PHONY : src/test/test_polynomial_roots.i

# target to preprocess a source file
src/test/test_polynomial_roots.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_polynomial_roots.cpp.i
.PHONY : src/test/test_polynomial_roots.cpp.i

src/test/test_polynomial_roots.s: src/test/test_polynomial_roots.cpp.s

.PHONY : src/test/test_polynomial_roots.s

# target to generate assembly for a file
src/test/test_polynomial_roots.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_polynomial_roots.cpp.s
.PHONY : src/test/test_polynomial_roots.cpp.s

src/test/test_project_points_to_surface.o: src/test/test_project_points_to_surface.cpp.o

.PHONY : src/test/test_project_points_to_surface.o

# target to build an object file
src/test/test_project_points_to_surface.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_project_points_to_surface.cpp.o
.PHONY : src/test/test_project_points_to_surface.cpp.o

src/test/test_project_points_to_surface.i: src/test/test_project_points_to_surface.cpp.i

.PHONY : src/test/test_project_points_to_surface.i

# target to preprocess a source file
src/test/test_project_points_to_surface.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_project_points_to_surface.cpp.i
.PHONY : src/test/test_project_points_to_surface.cpp.i

src/test/test_project_points_to_surface.s: src/test/test_project_points_to_surface.cpp.s

.PHONY : src/test/test_project_points_to_surface.s

# target to generate assembly for a file
src/test/test_project_points_to_surface.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_project_points_to_surface.cpp.s
.PHONY : src/test/test_project_points_to_surface.cpp.s

src/test/test_surface_primitive_sample.o: src/test/test_surface_primitive_sample.cpp.o

.PHONY : src/test/test_surface_primitive_sample.o

# target to build an object file
src/test/test_surface_primitive_sample.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_surface_primitive_sample.cpp.o
.PHONY : src/test/test_surface_primitive_sample.cpp.o

src/test/test_surface_primitive_sample.i: src/test/test_surface_primitive_sample.cpp.i

.PHONY : src/test/test_surface_primitive_sample.i

# target to preprocess a source file
src/test/test_surface_primitive_sample.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_surface_primitive_sample.cpp.i
.PHONY : src/test/test_surface_primitive_sample.cpp.i

src/test/test_surface_primitive_sample.s: src/test/test_surface_primitive_sample.cpp.s

.PHONY : src/test/test_surface_primitive_sample.s

# target to generate assembly for a file
src/test/test_surface_primitive_sample.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/test/test_surface_primitive_sample.cpp.s
.PHONY : src/test/test_surface_primitive_sample.cpp.s

src/vsa/quadratic_surface.o: src/vsa/quadratic_surface.cpp.o

.PHONY : src/vsa/quadratic_surface.o

# target to build an object file
src/vsa/quadratic_surface.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/vsa/quadratic_surface.cpp.o
.PHONY : src/vsa/quadratic_surface.cpp.o

src/vsa/quadratic_surface.i: src/vsa/quadratic_surface.cpp.i

.PHONY : src/vsa/quadratic_surface.i

# target to preprocess a source file
src/vsa/quadratic_surface.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/vsa/quadratic_surface.cpp.i
.PHONY : src/vsa/quadratic_surface.cpp.i

src/vsa/quadratic_surface.s: src/vsa/quadratic_surface.cpp.s

.PHONY : src/vsa/quadratic_surface.s

# target to generate assembly for a file
src/vsa/quadratic_surface.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/vsa/quadratic_surface.cpp.s
.PHONY : src/vsa/quadratic_surface.cpp.s

src/vsa/vsa_tri_mesh_wrapper.o: src/vsa/vsa_tri_mesh_wrapper.cpp.o

.PHONY : src/vsa/vsa_tri_mesh_wrapper.o

# target to build an object file
src/vsa/vsa_tri_mesh_wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/vsa/vsa_tri_mesh_wrapper.cpp.o
.PHONY : src/vsa/vsa_tri_mesh_wrapper.cpp.o

src/vsa/vsa_tri_mesh_wrapper.i: src/vsa/vsa_tri_mesh_wrapper.cpp.i

.PHONY : src/vsa/vsa_tri_mesh_wrapper.i

# target to preprocess a source file
src/vsa/vsa_tri_mesh_wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/vsa/vsa_tri_mesh_wrapper.cpp.i
.PHONY : src/vsa/vsa_tri_mesh_wrapper.cpp.i

src/vsa/vsa_tri_mesh_wrapper.s: src/vsa/vsa_tri_mesh_wrapper.cpp.s

.PHONY : src/vsa/vsa_tri_mesh_wrapper.s

# target to generate assembly for a file
src/vsa/vsa_tri_mesh_wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/csg_cpp_command.dir/build.make CMakeFiles/csg_cpp_command.dir/src/vsa/vsa_tri_mesh_wrapper.cpp.s
.PHONY : src/vsa/vsa_tri_mesh_wrapper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... csg_cpp_command"
	@echo "... edit_cache"
	@echo "... gco"
	@echo "... example"
	@echo "... src/command/add_separator_command.o"
	@echo "... src/command/add_separator_command.i"
	@echo "... src/command/add_separator_command.s"
	@echo "... src/command/bhc_command.o"
	@echo "... src/command/bhc_command.i"
	@echo "... src/command/bhc_command.s"
	@echo "... src/command/clean_csg_command.o"
	@echo "... src/command/clean_csg_command.i"
	@echo "... src/command/clean_csg_command.s"
	@echo "... src/command/csg_flag_command.o"
	@echo "... src/command/csg_flag_command.i"
	@echo "... src/command/csg_flag_command.s"
	@echo "... src/command/csg_mesh_diff_command.o"
	@echo "... src/command/csg_mesh_diff_command.i"
	@echo "... src/command/csg_mesh_diff_command.s"
	@echo "... src/command/equiv_class_command.o"
	@echo "... src/command/equiv_class_command.i"
	@echo "... src/command/equiv_class_command.s"
	@echo "... src/command/equiv_class_flag_command.o"
	@echo "... src/command/equiv_class_flag_command.i"
	@echo "... src/command/equiv_class_flag_command.s"
	@echo "... src/command/genetic_command.o"
	@echo "... src/command/genetic_command.i"
	@echo "... src/command/genetic_command.s"
	@echo "... src/command/hausdorff_command.o"
	@echo "... src/command/hausdorff_command.i"
	@echo "... src/command/hausdorff_command.s"
	@echo "... src/command/legacy_sketch_tree_command.o"
	@echo "... src/command/legacy_sketch_tree_command.i"
	@echo "... src/command/legacy_sketch_tree_command.s"
	@echo "... src/command/level_set_command.o"
	@echo "... src/command/level_set_command.i"
	@echo "... src/command/level_set_command.s"
	@echo "... src/command/mesh_flag_command.o"
	@echo "... src/command/mesh_flag_command.i"
	@echo "... src/command/mesh_flag_command.s"
	@echo "... src/command/primitive_command.o"
	@echo "... src/command/primitive_command.i"
	@echo "... src/command/primitive_command.s"
	@echo "... src/command/primitive_local_command.o"
	@echo "... src/command/primitive_local_command.i"
	@echo "... src/command/primitive_local_command.s"
	@echo "... src/command/ransac_command.o"
	@echo "... src/command/ransac_command.i"
	@echo "... src/command/ransac_command.s"
	@echo "... src/command/remove_equiv_class_command.o"
	@echo "... src/command/remove_equiv_class_command.i"
	@echo "... src/command/remove_equiv_class_command.s"
	@echo "... src/command/remove_prim_command.o"
	@echo "... src/command/remove_prim_command.i"
	@echo "... src/command/remove_prim_command.s"
	@echo "... src/command/surface_sample_command.o"
	@echo "... src/command/surface_sample_command.i"
	@echo "... src/command/surface_sample_command.s"
	@echo "... src/command/traverse_tree_command.o"
	@echo "... src/command/traverse_tree_command.i"
	@echo "... src/command/traverse_tree_command.s"
	@echo "... src/command/tree_info_command.o"
	@echo "... src/command/tree_info_command.i"
	@echo "... src/command/tree_info_command.s"
	@echo "... src/command/volume_sample_command.o"
	@echo "... src/command/volume_sample_command.i"
	@echo "... src/command/volume_sample_command.s"
	@echo "... src/common/arg_parser.o"
	@echo "... src/common/arg_parser.i"
	@echo "... src/common/arg_parser.s"
	@echo "... src/common/file_helper.o"
	@echo "... src/common/file_helper.i"
	@echo "... src/common/file_helper.s"
	@echo "... src/common/math_helper.o"
	@echo "... src/common/math_helper.i"
	@echo "... src/common/math_helper.s"
	@echo "... src/common/polynomial.o"
	@echo "... src/common/polynomial.i"
	@echo "... src/common/polynomial.s"
	@echo "... src/csg/csg_cone_node.o"
	@echo "... src/csg/csg_cone_node.i"
	@echo "... src/csg/csg_cone_node.s"
	@echo "... src/csg/csg_cube_node.o"
	@echo "... src/csg/csg_cube_node.i"
	@echo "... src/csg/csg_cube_node.s"
	@echo "... src/csg/csg_cylinder_node.o"
	@echo "... src/csg/csg_cylinder_node.i"
	@echo "... src/csg/csg_cylinder_node.s"
	@echo "... src/csg/csg_internal_node.o"
	@echo "... src/csg/csg_internal_node.i"
	@echo "... src/csg/csg_internal_node.s"
	@echo "... src/csg/csg_node.o"
	@echo "... src/csg/csg_node.i"
	@echo "... src/csg/csg_node.s"
	@echo "... src/csg/csg_sphere_node.o"
	@echo "... src/csg/csg_sphere_node.i"
	@echo "... src/csg/csg_sphere_node.s"
	@echo "... src/csg/csg_torus_node.o"
	@echo "... src/csg/csg_torus_node.i"
	@echo "... src/csg/csg_torus_node.s"
	@echo "... src/csg/scad_file_parser.o"
	@echo "... src/csg/scad_file_parser.i"
	@echo "... src/csg/scad_file_parser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mesh/intersection.o"
	@echo "... src/mesh/intersection.i"
	@echo "... src/mesh/intersection.s"
	@echo "... src/mesh/kd_tree.o"
	@echo "... src/mesh/kd_tree.i"
	@echo "... src/mesh/kd_tree.s"
	@echo "... src/mesh/kd_tree_node.o"
	@echo "... src/mesh/kd_tree_node.i"
	@echo "... src/mesh/kd_tree_node.s"
	@echo "... src/mesh/level_set_helper.o"
	@echo "... src/mesh/level_set_helper.i"
	@echo "... src/mesh/level_set_helper.s"
	@echo "... src/mesh/tri_mesh.o"
	@echo "... src/mesh/tri_mesh.i"
	@echo "... src/mesh/tri_mesh.s"
	@echo "... src/primitive/conical_surface.o"
	@echo "... src/primitive/conical_surface.i"
	@echo "... src/primitive/conical_surface.s"
	@echo "... src/primitive/cylindrical_surface.o"
	@echo "... src/primitive/cylindrical_surface.i"
	@echo "... src/primitive/cylindrical_surface.s"
	@echo "... src/primitive/plane_surface.o"
	@echo "... src/primitive/plane_surface.i"
	@echo "... src/primitive/plane_surface.s"
	@echo "... src/primitive/spherical_surface.o"
	@echo "... src/primitive/spherical_surface.i"
	@echo "... src/primitive/spherical_surface.s"
	@echo "... src/primitive/surface_primitive.o"
	@echo "... src/primitive/surface_primitive.i"
	@echo "... src/primitive/surface_primitive.s"
	@echo "... src/primitive/toric_surface.o"
	@echo "... src/primitive/toric_surface.i"
	@echo "... src/primitive/toric_surface.s"
	@echo "... src/ransac/cgal_ransac_wrapper.o"
	@echo "... src/ransac/cgal_ransac_wrapper.i"
	@echo "... src/ransac/cgal_ransac_wrapper.s"
	@echo "... src/test/test.o"
	@echo "... src/test/test.i"
	@echo "... src/test/test.s"
	@echo "... src/test/test_compute_level_set.o"
	@echo "... src/test/test_compute_level_set.i"
	@echo "... src/test/test_compute_level_set.s"
	@echo "... src/test/test_generate_random_ints.o"
	@echo "... src/test/test_generate_random_ints.i"
	@echo "... src/test/test_generate_random_ints.s"
	@echo "... src/test/test_grad_norm_vector.o"
	@echo "... src/test/test_grad_norm_vector.i"
	@echo "... src/test/test_grad_norm_vector.s"
	@echo "... src/test/test_initialize_surface_parameters.o"
	@echo "... src/test/test_initialize_surface_parameters.i"
	@echo "... src/test/test_initialize_surface_parameters.s"
	@echo "... src/test/test_integral.o"
	@echo "... src/test/test_integral.i"
	@echo "... src/test/test_integral.s"
	@echo "... src/test/test_intersect.o"
	@echo "... src/test/test_intersect.i"
	@echo "... src/test/test_intersect.s"
	@echo "... src/test/test_is_inside.o"
	@echo "... src/test/test_is_inside.i"
	@echo "... src/test/test_is_inside.s"
	@echo "... src/test/test_l21_matrix.o"
	@echo "... src/test/test_l21_matrix.i"
	@echo "... src/test/test_l21_matrix.s"
	@echo "... src/test/test_l2_matrix.o"
	@echo "... src/test/test_l2_matrix.i"
	@echo "... src/test/test_l2_matrix.s"
	@echo "... src/test/test_linear_least_square_plane_fit.o"
	@echo "... src/test/test_linear_least_square_plane_fit.i"
	@echo "... src/test/test_linear_least_square_plane_fit.s"
	@echo "... src/test/test_polynomial_roots.o"
	@echo "... src/test/test_polynomial_roots.i"
	@echo "... src/test/test_polynomial_roots.s"
	@echo "... src/test/test_project_points_to_surface.o"
	@echo "... src/test/test_project_points_to_surface.i"
	@echo "... src/test/test_project_points_to_surface.s"
	@echo "... src/test/test_surface_primitive_sample.o"
	@echo "... src/test/test_surface_primitive_sample.i"
	@echo "... src/test/test_surface_primitive_sample.s"
	@echo "... src/vsa/quadratic_surface.o"
	@echo "... src/vsa/quadratic_surface.i"
	@echo "... src/vsa/quadratic_surface.s"
	@echo "... src/vsa/vsa_tri_mesh_wrapper.o"
	@echo "... src/vsa/vsa_tri_mesh_wrapper.i"
	@echo "... src/vsa/vsa_tri_mesh_wrapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

