#!/bin/sh
if [ -z "$SKETCH_HOME" ];
then
echo "You need to set the \$SKETCH_HOME environment variable to be the path to the SKETCH distribution; This is needed to find the SKETCH header files needed to compile your program." >&2;
exit 1;
fi
g++ -I "$SKETCH_HOME/include" -o rotated_cuboid_0_0 rotated_cuboid_0_0.cpp rotated_cuboid_0_0_test.cpp
./rotated_cuboid_0_0
