#!/bin/sh
if [ -z "$SKETCH_HOME" ];
then
echo "You need to set the \$SKETCH_HOME environment variable to be the path to the SKETCH distribution; This is needed to find the SKETCH header files needed to compile your program." >&2;
exit 1;
fi
g++ -I "$SKETCH_HOME/include" -o two_cuboids_0_0 two_cuboids_0_0.cpp two_cuboids_0_0_test.cpp
./two_cuboids_0_0
