#!/bin/sh
if [ -z "$SKETCH_HOME" ];
then
echo "You need to set the \$SKETCH_HOME environment variable to be the path to the SKETCH distribution; This is needed to find the SKETCH header files needed to compile your program." >&2;
exit 1;
fi
g++ -I "$SKETCH_HOME/include" -o spot_4_0 spot_4_0.cpp spot_4_0_test.cpp
./spot_4_0
